### ISSUE TITLE
Can Pull Out Everyones Car 

### ISSUE THREAD

**Issue by dougiebeatz** [LukeWasTakenn/luke_garages#37] opened 2022-01-10 01:20 UTC
Hello Luke , 

i recently did your update that just came out , everything was working fine , then some reason everyones car was gone . so i updated . now i can pull out everyones car from the legion square garage . 

only thing thats been edited is the config, No Errors

**Comment by dougiebeatz** [comment] 2022-01-10 01:47
After restart the script getting this error https://gyazo.com/3c4a636bc0666dfe2cd9cfabfd17cd04

**Comment by LukeWasTakenn** [comment] 2022-01-10 07:30
Hmm can you put your config file into a pastebin and send the link?

**Comment by dougiebeatz** [comment] 2022-01-10 18:31
https://pastebin.com/wcBG43Td

**Comment by LukeWasTakenn** [comment] 2022-01-10 19:32
Not something I'm able to reproduce, issue seems to be something related to your plates maybe...?

Does the previous version work fine?

**Comment by dougiebeatz** [comment] 2022-01-10 19:49
Previous version worked fine . i havent changed anything to plates since day 1 of opening the server ( 7 months ago ) 

but yeah previous version worked fine , every once in a while it would throw a garaged car into impound but

**Comment by LukeWasTakenn** [comment] 2022-01-10 19:54
I've changed nothing to do with fetching vehicles other than added an option for job vehicles

Can I see the data in your `owned_vehicles` table? 🤔

**Comment by dougiebeatz** [comment] 2022-01-10 19:58
I was using Renzuzu_garages before finding yours , and already had options in for job vehicles , same with t1gers_cardealership 

idk if thats conflicting , here is the Database for owned_vehicles

**Comment by LukeWasTakenn** [comment] 2022-01-10 20:09
Yeah I don't see anything wrong with those columns really not sure what's going on, doesn't help that no one else reported this issue either 🤷

**Comment by dougiebeatz** [comment] 2022-01-10 20:21
yeah tbh its super weird . after update , i could pull out everyones car at legion , i restart the server then nothing shows up . i appreciate your time .

**Comment by Vumono** [comment] 2022-01-12 20:21
I have this issue aswell

**Comment by LukeWasTakenn** [comment] 2022-01-12 23:43
I can't reproduce this with -cl2 so it leads me to think it's something on your side being weird...? Really not sure what's happening.

**Comment by LukeWasTakenn** [comment] 2022-01-18 19:31
I'll close this for now and keep an eye out on it, will definitely need looking into if it turns out to be a common issue, but doesn't seem to be so far.

**Closed by LukeWasTakenn** 2022-01-18 19:31 UTC

**Comment by LukeWasTakenn** [comment] 2022-01-18 20:26
This should now be resolved in latest commit.
