### ISSUE TITLE
2.5.0 Feedback

### ISSUE THREAD

**Issue by Zzeyy** [LukeWasTakenn/luke_garages#70] opened 2022-03-13 10:32 UTC
Hi,
maybe don't close all the issues.
It's nice to keep it clean, yeah, but as you asked for a feedback I think it would be better not to make hundreds of issues for one thing.

Anyway, here's the first thing.
```
[      script:oxmysql] SCRIPT ERROR in promise (unhandled): Error: luke_garages was unable to execute a query!
[      script:oxmysql] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'stored, health, garage, job FROM owned_vehicles WHERE owner = 'f42eefdb0c65667a8' at line 1
[      script:oxmysql] SELECT plate, vehicle, stored, health, garage, job FROM owned_vehicles WHERE owner = 'f42eefdb0c65667a86d9c83a04754b4a4b7124d2' AND type = 'car'
[      script:oxmysql] > rawQuery (@oxmysql/dist/build.js:21702)
[      script:oxmysql] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:oxmysql] 
```
I get this issue after updating the script to 2.5.0,
I'll try wiping the tables and making them again.

**Comment by Zzeyy** [comment] 2022-03-13 10:36
From comparing my database to the sql file provided in 2.5.0 release I can say
that wiping the table wouldn't fix anything, just make it worse by losing all of the saved vehicles.

![image](https://user-images.githubusercontent.com/97387354/158055604-08418eb2-5a45-4648-bed4-252cb17195ae.png)

**Comment by LukeWasTakenn** [comment] 2022-03-13 10:51
You can still comment on an issue even after I close it, and you can do so until I lock the conversation for that issue.

Also I'm not getting this error with the query at all, interesting

**Comment by Zzeyy** [comment] 2022-03-13 10:53
I'll try to restart the whole VPS the server is running on.

**Comment by LukeWasTakenn** [comment] 2022-03-13 10:56
No that's not the issue, it's complaining about a syntax error obviously, it's just that I don't see any error in the syntax and if there was how does it work on my end? lol

**Comment by Zzeyy** [comment] 2022-03-13 10:59
I wasn't restarting just because this error, no.

**Comment by Zzeyy** [comment] 2022-03-13 10:59
> 

But the error wasn't showing on a previous release.

**Comment by Zzeyy** [comment] 2022-03-13 11:00
I didn't touch MySql that I'm running since the day I created a database for my current fivem server,
which is like a week and a half, also, if it indeed was a mistake on my side, how could other scripts work?

**Comment by Zzeyy** [comment] 2022-03-13 11:04
![image](https://user-images.githubusercontent.com/97387354/158056537-efa08395-d57a-4a07-b73f-5df24670ee94.png)

**Comment by Zzeyy** [comment] 2022-03-13 11:04
Now I'll replace even the config file.

**Comment by Zzeyy** [comment] 2022-03-13 11:07
WTF, it does work now 🙄

**Comment by Zzeyy** [comment] 2022-03-13 11:17
![image](https://user-images.githubusercontent.com/97387354/158056937-7e5331ca-761e-4802-b946-eb46a2a18281.png)

Okay and this is what? 🤣

**Comment by Zzeyy** [comment] 2022-03-13 11:17
Clicking on the bottom button even spawns the car twice lol.

**Comment by Zzeyy** [comment] 2022-03-13 11:19
![image](https://user-images.githubusercontent.com/97387354/158056988-e65dd3d4-0548-40d8-a97a-253fb94360a8.png)
And clicking on this button opens the spawn menu of one of the cars.

**Comment by Zzeyy** [comment] 2022-03-13 11:21
![image](https://user-images.githubusercontent.com/97387354/158057088-9179ed13-5a88-49c8-9e6a-9e1064fbff6b.png)
Okay they are duplicated...

**Comment by LukeWasTakenn** [comment] 2022-03-13 12:11
Seems like you have the the resource running twice.  I never encountered these issues.

**Comment by Zzeyy** [comment] 2022-03-13 12:21
I restarted the server, with Luke Garages updated to 2.5.0, but using the 2.4.3 config.
I cannot open the garage, which means the config has been indeed changed.

Any way to convert the config?

**Comment by LukeWasTakenn** [comment] 2022-03-13 12:23
The config file hasn't been touched in 2 months.

**Comment by Zzeyy** [comment] 2022-03-13 12:24
Then the 2.5.0 release is not working for me.

**Comment by Zzeyy** [comment] 2022-03-13 12:24
I guess I'll stick to the 2.4.3.

**Comment by LukeWasTakenn** [comment] 2022-03-13 12:40
I'll watch feedback from other people and if more people report the same thing then I'll know it's a wide spread issue.

**Comment by LukeWasTakenn** [comment] 2022-03-14 20:31
So I'm pretty sure I found the cause of this for you, `stored` seems to be a reserved keyword in MySQL so it would seem that it's not looking for the column but rather the keyword itself, causing it to throw the syntax error.

Though I am still confused to as how this is happening to you and I don't experience this issue at all.

**Comment by LukeWasTakenn** [comment] 2022-03-14 22:34
I pushed a possible fix for this, so try the latest commit and see if that fixes it for you.

**Comment by Zzeyy** [comment] 2022-03-16 19:28
![image](https://user-images.githubusercontent.com/97387354/158674269-a8fe2ae7-f469-49e1-a55a-3e7f654800ba.png)
![image](https://user-images.githubusercontent.com/97387354/158674284-c92b9b00-72b7-4756-9b77-7a30148cadb1.png)

So the cars are on the impound, but nothing happens when I select a car I want to return.

**Server Console Error**
```
[  script:es_extended] [WARNING] Server callback "luke_garages:PayImpound" does not exist. Please Check The Server File for Errors!
[  script:es_extended] [WARNING] Server callback "luke_garages:PayImpound" does not exist. Please Check The Server File for Errors!
[  script:es_extended] [WARNING] Server callback "luke_garages:PayImpound" does not exist. Please Check The Server File for Errors!
```

**Comment by LukeWasTakenn** [comment] 2022-03-16 19:57
The PayImpound event was removed, seems like you haven't updated the resource properly

**Comment by Zzeyy** [comment] 2022-03-16 22:17
I think I even restarted the server later on and this appeared later on.
I'll try again tomorrow.

**Closed** 2022-03-25 18:25 UTC
