### ISSUE TITLE
several same vehicles are not displayed

### ISSUE THREAD

**Issue by janwichmann12** [LukeWasTakenn/luke_garages#90] opened 2022-05-16 05:10 UTC
I have 3x the same vehicle only with different license plates but only one of them is listed

**Comment by LukeWasTakenn** [comment] 2022-05-16 22:07
Can reproduce, this is likely happening because the names of the vehicles are the same and I'm passing them as keys, which you can't have duplicates of.

Will be fixed.

**Comment by LukeWasTakenn** [comment] 2022-05-16 22:18
Resolved in commit fe4b857e7df4ab3281506e8054039c41933f8898

**Closed by LukeWasTakenn** 2022-05-16 22:18 UTC
Labels: bug
