### ISSUE TITLE
Impound and garages

### ISSUE THREAD

**Issue by Therealhellsaint** [LukeWasTakenn/luke_garages#25] opened 2021-12-21 00:35 UTC
When pulling a vehicle out of the garage it will become "not in garage"  and thats perfect but from the moment the vehicle is out you can park it far away and take it out of the impound and create 2 cars with the same place etc .
it should check if the entity is out in the world or not cause if it is the impound should not work even when blowed up or went in the water it.

**Comment by LukeWasTakenn** [comment] 2021-12-21 14:07
Seems to be another issue with server sided spawning. It works fine when you have `Config.ServerSpawn` set to false.

For some reason when you spawn a vehicle with server sided spawning it doesn't find the entity in the world if it's too far away from the player.

**Comment by Therealhellsaint** [comment] 2021-12-21 14:24
Asides from the config option is there a way to fix this without causing more issues?

**Comment by LukeWasTakenn** [comment] 2021-12-21 14:25
Not really, I need to look into a good way to handle the server spawning stuff since it's quite scuffed now, just haven't gotten around to it.

**Comment by Therealhellsaint** [comment] 2021-12-21 14:31
Thats a bummer i really really like this garage system is looks amazing and the way it works is mega cool if i find anything ill post it here to try to help i hope you manage this fix this this garage system is going to be the best out there

**Comment by Therealhellsaint** [comment] 2021-12-22 11:40
Was reading some posts i found this native that can be useful but not 100% sure

SetNetworkIdExistsOnAllMachines(vehicle,true)

Might neee to so some reaserch on it it should check if the entity is spawned

**Comment by LukeWasTakenn** [comment] 2021-12-22 15:30
Hmm I don't think so, the issue is that the player doesn't get proper ownership of the vehicle, to fix that I'd need to seat the player into the vehicle when it spawns

**Comment by LukeWasTakenn** [comment] 2021-12-22 17:04
This should now be fixed with 523d99ef18bda98d742bd5bc2d607c7fdde7ab5a.

Still need to figure out entity ownership though.

**Closed by LukeWasTakenn** 2021-12-22 17:04 UTC

**Comment by LukeWasTakenn** [comment] 2021-12-22 18:40
As of 6472ed14196065604d0e49a2a6bfab44df3405a4 server spawning should work as intended.
